### ISSUE TITLE
Could not install the package on windows.

### ISSUE THREAD

**Issue by zuofengli** [biocommons/hgvs#470]
using pip install hgvs to install the package. However, I meet following error.

Collecting pysam (from biocommons.seqrepo->hgvs)
  Using cached pysam-0.12.0.1.tar.gz
    Complete output from command python setup.py egg_info:
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    '.' is not recognized as an internal or external command,
    operable program or batch file.
    # pysam: no cython available - using pre-compiled C
    # pysam: htslib mode is shared
    # pysam: HTSLIB_CONFIGURE_OPTIONS=None
    # pysam: htslib configure options: None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\zuofeng\appdata\local\temp\pip-build-brwg8v\pysam\setup.py", line 220, in <module>
        htslib_make_options = run_make_print_config()
      File "c:\users\zuofeng\appdata\local\temp\pip-build-brwg8v\pysam\setup.py", line 63, in run_make_print_config
        stdout = subprocess.check_output(["make", "-s", "print-config"])
      File "C:\Python27\lib\subprocess.py", line 568, in check_output
        process = Popen(stdout=PIPE, *popenargs, **kwargs)
      File "C:\Python27\lib\subprocess.py", line 711, in __init__
        errread, errwrite)
      File "C:\Python27\lib\subprocess.py", line 948, in _execute_child
        startupinfo)
    WindowsError: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\zuofeng\appdata\local\temp\pip-build-brwg8v\pysam\

**Comment by reece** [comment]
hgvs was not designed to work on windows. I have no expectation that it would or that we would find time do support it.  My recommendation is to install in a docker image.
