### ISSUE TITLE
Out-of-bounds coordinates despite being a "relevant" transcript

### ISSUE THREAD

**Issue by stephan-hutter** [biocommons/hgvs#477]
I am trying to map a genomic variant to any overlapping transcripts and get an unexpected error. Here is my code:

var_g = hp.parse_hgvs_variant('NC_000001.10:g.16890649G>A')
transcripts = am.relevant_transcripts(var_g)
--- This results in one transcript: NM_017940.4 ---
var_c = am.g_to_c(var_g, 'NM_017940.4')

And the resulting error:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    var_c = am.g_to_c(var_g, 'NM_017940.4')
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/assemblymapper.py", line 82, in g_to_c
    var_out = super(AssemblyMapper, self).g_to_c(var_g, tx_ac, alt_aln_method=self.alt_aln_method)
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/variantmapper.py", line 197, in g_to_c
    pos_c = tm.g_to_c(var_g.posedit.pos)
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/transcriptmapper.py", line 250, in g_to_c
    return self.n_to_c(self.g_to_n(g_interval))
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/transcriptmapper.py", line 147, in g_to_n
    start_bo = map_g_to_n_pos(g_interval.start.base)[0:2]
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/transcriptmapper.py", line 118, in map_g_to_n_pos
    frs, fre = self.im.map_ref_to_tgt(g_ci[0] - self.gc_offset, g_ci[1] - self.gc_offset, max_extent=False)
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/intervalmapper.py", line 128, in map_ref_to_tgt
    return self._map(self.ref_intervals, self.tgt_intervals, start_i, end_i, max_extent)
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/intervalmapper.py", line 154, in _map
    si, ei = iv_map(from_ivs, to_ivs, from_start_i, from_end_i, max_extent)
  File "/home/bioinfo/anaconda3/envs/hgvs/lib/python2.7/site-packages/hgvs/intervalmapper.py", line 145, in iv_map
    raise HGVSInvalidIntervalError("start or end or both are beyond the bounds of transcript record")
hgvs.exceptions.HGVSInvalidIntervalError: start or end or both are beyond the bounds of transcript record

I assumed that relevant transcripts should always overlap with genomic coordinates, so I am unsure what the source of this error could be. BTW, Mutalyzer.nl gives me a result:

Chromosomal variant
NC_000001.10:g.16890649G>A

Found transcripts in variant region
NBPF1     :	NM_017940.4:c.3158C>T
		NM_017940.3:c.3158C>T

**Comment by reece** [comment]
Confirmed with GRCh37 and 38. Investigating now.

```
>>> var_g = hp.parse_hgvs_variant('NC_000001.10:g.16890649G>A')
>>> am37.relevant_transcripts(var_g)
['NM_017940.4']
>>> am38.relevant_transcripts(var_g)
['NM_017940.4']
>>> am37.g_to_c(var_g, 'NM_017940.4')
Traceback (most recent call last):
  File "<ipython-input-11-5f2d9c52bc5b>", line 1, in <module>
    am37.g_to_c(var_g, 'NM_017940.4')
  File "/home/reece/projects/biocommons/hgvs/hgvs/assemblymapper.py", line 82, in g_to_c
    var_out = super(AssemblyMapper, self).g_to_c(var_g, tx_ac, alt_aln_method=self.alt_aln_method)
  File "/home/reece/projects/biocommons/hgvs/hgvs/variantmapper.py", line 217, in g_to_c
    pos_c = tm.g_to_c(var_g.posedit.pos)
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 252, in g_to_c
    return self.n_to_c(self.g_to_n(g_interval))
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 146, in g_to_n
    frs, frs_offset, frs_cigar = self._map(from_pos=self.ref_pos, to_pos=self.tgt_pos, pos=grs, base="start")
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 120, in _map
    raise HGVSInvalidIntervalError("Position is beyond the bounds of transcript record")
HGVSInvalidIntervalError: Position is beyond the bounds of transcript record

>>> am38.g_to_c(var_g, 'NM_017940.4')
Traceback (most recent call last):
  File "<ipython-input-12-561291b467b9>", line 1, in <module>
    am38.g_to_c(var_g, 'NM_017940.4')
  File "/home/reece/projects/biocommons/hgvs/hgvs/assemblymapper.py", line 82, in g_to_c
    var_out = super(AssemblyMapper, self).g_to_c(var_g, tx_ac, alt_aln_method=self.alt_aln_method)
  File "/home/reece/projects/biocommons/hgvs/hgvs/variantmapper.py", line 217, in g_to_c
    pos_c = tm.g_to_c(var_g.posedit.pos)
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 252, in g_to_c
    return self.n_to_c(self.g_to_n(g_interval))
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 146, in g_to_n
    frs, frs_offset, frs_cigar = self._map(from_pos=self.ref_pos, to_pos=self.tgt_pos, pos=grs, base="start")
  File "/home/reece/projects/biocommons/hgvs/hgvs/alignmentmapper.py", line 120, in _map
    raise HGVSInvalidIntervalError("Position is beyond the bounds of transcript record")
HGVSInvalidIntervalError: Position is beyond the bounds of transcript record
```

**Comment by reece** [comment]
I added these tests (`tests/issues/test_477.py`)
```Python
    {"c": "NM_145171.3:c.-63A>G", "g": "NC_000014.8:g.63785599T>C", "rs": "GPHB5/GRCh37/rs1299953722", "ex": HGVSInvalidIntervalError },
    {"c": "NM_145171.3:c.-56G>A", "g": "NC_000014.8:g.63785592C>T", "rs": "GPHB5/GRCh37/rs982881702"  },
    {"c": "NM_145171.3:c.2T>C",   "g": "NC_000014.8:g.63784562A>G", "rs": "GPHB5/GRCh37/rs1221379530"  },
    {"c": "NM_145171.3:c.388A>G", "g": "NC_000014.8:g.63779647T>C", "rs": "GPHB5/GRCh37/rs1380832691" },
    {"c": "NM_145171.3:c.*4C>T",  "g": "NC_000014.8:g.63779638G>A", "rs": "GPHB5/GRCh37/rs753041439"  },
    {"c": "NM_145171.3:c.*84A>G", "g": "NC_000014.8:g.63779558T>C", "rs": "GPHB5/GRCh37/rs1204774077" },
    {"c": "NM_145171.3:c.*99G>A", "g": "NC_000014.8:g.63779543C>T", "rs": "GPHB5/GRCh37/rs144659601", "ex": HGVSInvalidIntervalError  },

    # GPHB5, GRCh37 https://www.ncbi.nlm.nih.gov/gene/122876
    {"c": "NM_145171.3:c.-63A>G", "g": "NC_000014.9:g.63318885T>C", "rs": "GPHB5/GRCh38/rs1299953722", "ex": HGVSInvalidIntervalError },
    {"c": "NM_145171.3:c.-56G>A", "g": "NC_000014.9:g.63318878C>T", "rs": "GPHB5/GRCh38/rs982881702"  },
    {"c": "NM_145171.3:c.2T>C",   "g": "NC_000014.9:g.63317848A>G", "rs": "GPHB5/GRCh38/rs1221379530"  },
    {"c": "NM_145171.3:c.388A>G", "g": "NC_000014.9:g.63312933T>C", "rs": "GPHB5/GRCh38/rs1380832691" },
    {"c": "NM_145171.3:c.*4C>T",  "g": "NC_000014.9:g.63312924G>A", "rs": "GPHB5/GRCh38/rs753041439"  },
    {"c": "NM_145171.3:c.*84A>G", "g": "NC_000014.9:g.63312844T>C", "rs": "GPHB5/GRCh38/rs1204774077" },
    {"c": "NM_145171.3:c.*99G>A", "g": "NC_000014.9:g.63312829C>T", "rs": "GPHB5/GRCh38/rs144659601", "ex": HGVSInvalidIntervalError  },

    # COX6A2 https://www.ncbi.nlm.nih.gov/gene/1339
    {"c": "NM_005205.3:c.-106G>A", "g": "NC_000016.10:g.31428431C>T", "rs": "COX6A2/GRCh38/rs1033792906", "ex": HGVSInvalidIntervalError },
    {"c": "NM_005205.3:c.-96C>T",  "g": "NC_000016.10:g.31428421G>A", "rs": "COX6A2/GRCh38/rs755670336" },
    {"c": "NM_005205.3:c.2T>C",    "g": "NC_000016.10:g.31428324A>G", "rs": "COX6A2/GRCh38/rs200780049" },
    {"c": "NM_005205.3:c.293G>A",  "g": "NC_000016.10:g.31427775C>T", "rs": "COX6A2/GRCh38/rs764753905" },
    {"c": "NM_005205.3:c.*3C>T",   "g": "NC_000016.10:g.31427771G>A", "rs": "COX6A2/GRCh38/rs909673485" },
    {"c": "NM_005205.3:c.*42G>C",  "g": "NC_000016.10:g.31427732C>G", "rs": "COX6A2/GRCh38/rs375688325" },
    {"c": "NM_005205.3:c.*43A>G",  "g": "NC_000016.10:g.31427731T>C", "rs": "COX6A2/GRCh38/rs961248971" },
    {"c": "NM_005205.3:c.*44G>A",  "g": "NC_000016.10:g.31427730C>T", "rs": "COX6A2/GRCh38/rs756406653", "ex": HGVSInvalidIntervalError },
```

None of these fail. 

On further investigation of [NBPF](https://www.ncbi.nlm.nih.gov/gene/55672), it's clear that NM_017940.4 is an odd transcript. It has no defined exons in the genbank record but does have a CDS. The visual display at NCBI shows the transcript in purple, and the 5' end has a glyph that I've never seen before. NCBI is trying to tell us something about this transcript, but the message is lost on me.
