### ISSUE TITLE
SeqRepo files left open after hdp.close()?

### ISSUE THREAD

**Issue by jfreidin** [biocommons/hgvs#520]
Hi @reece,
During a long running process that was opening and closing many `hdp` connections, eventually failure with messaging below occurred. This suggests that `SeqRepo` files are being left open after hdp.close() is called. I reviewed what documentation and code I could find but didn't find a smoking gun.

I've worked around this by switching to process-global pooled hdp connections. That hasn't caused any problems and is presumably more efficient.
Best,
Jonathan

```WARNING:hgvs.dataproviders.uta:Closing connection; future mapping and validation will fail.
WARNING:hgvs.dataproviders.uta:Closing connection; future mapping and validation will fail.
WARNING:hgvs.dataproviders.uta:Closing connection; future mapping and validation will fail.
[E::fai_load3_core] Failed to open FASTA file /usr/local/share/seqrepo/2018-08-21/sequences/2016/0824/050333/1472015013.075431.fa.bgz
Traceback (most recent call last):
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
    context_bases=self.context_bases)
  File "pipecycle/readclassifier.py", line 9, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
  File "pipecycle/shortvariant.py", line 29, in __init__
    self.variant_p = assembly_mapper.c_to_p(self.variant_c)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/assemblymapper.py", line 117, in c_to_p
    var_out = super(AssemblyMapper, self).c_to_p(var_c)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/variantmapper.py", line 347, in c_to_p
    self._validator.validate(var_c)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/validator.py", line 33, in validate
    return self._ivr.validate(var, strict) and self._evr.validate(var, strict)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/validator.py", line 72, in validate
    (res, msg) = self._ref_is_valid(var)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/validator.py", line 96, in _ref_is_valid
    var_x = self.vm.c_to_n(var) if var.type == "c" else var
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/variantmapper.py", line 300, in c_to_n
    self._replace_reference(var_n)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/variantmapper.py", line 394, in _replace_reference
    seq = self.hdp.get_seq(var.ac, pos.start.base - 1, pos.end.base)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/decorators/lru_cache.py", line 186, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 230, in get_seq
    return self.seqfetcher.fetch_seq(ac, start_i, end_i)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/seqfetcher.py", line 53, in fetch_seq
    return self.fetcher(ac, start_i, end_i)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/seqfetcher.py", line 41, in _fetch_seq_seqrepo
    return sr.fetch(ac, start_i, end_i)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqrepo.py", line 91, in fetch
    return self.sequences.fetch(seq_ids.pop(), start, end)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 117, in fetch
    fabgz = self._open_for_reading(path)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/py2compat/_lru_cache.py", line 139, in wrapper
    result = user_function(*args, **kwds)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/fastadir/fastadir.py", line 184, in _open_for_reading
    return FabgzReader(path)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/fastadir/fabgz.py", line 57, in __init__
    self._fh = FastaFile(filename)
  File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 183, in pysam.libcfaidx.FastaFile._open
IOError: error when opening file `/usr/local/share/seqrepo/2018-08-21/sequences/2016/0824/050333/1472015013.075431.fa.bgz`
Traceback (most recent call last):
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
    context_bases=self.context_bases)
  File "pipecycle/readclassifier.py", line 9, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
  File "pipecycle/shortvariant.py", line 15, in __init__
    hdp = hgvs.dataproviders.uta.connect()
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 107, in connect
    conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name, mode=mode, cache=cache)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 477, in __init__
    super(UTA_postgresql, self).__init__(url, mode, cache)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 196, in __init__
    self.seqfetcher = SeqFetcher()
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/seqfetcher.py", line 38, in __init__
    sr = SeqRepo(seqrepo_dir)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqrepo.py", line 58, in __init__
    self.aliases = SeqAliasDB(self._db_path, writeable=self._writeable)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqaliasdb/seqaliasdb.py", line 33, in __init__
OperationalError: unable to open database file
```
and
```OperationalError: unable to open database file
WARNING:hgvs.dataproviders.uta:Closing connection; future mapping and validation will fail.
IOError: error when opening file `/usr/local/share/seqrepo/2018-08-21/sequences/2016/0824/050214/1472014934.4127045.fa.bgz`
Traceback (most recent call last):
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
    context_bases=self.context_bases)
  File "pipecycle/readclassifier.py", line 9, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
  File "pipecycle/shortvariant.py", line 15, in __init__
    hdp = hgvs.dataproviders.uta.connect()
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 107, in connect
    conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name, mode=mode, cache=cache)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 477, in __init__
Traceback (most recent call last):
    super(UTA_postgresql, self).__init__(url, mode, cache)
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 196, in __init__
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
    context_bases=self.context_bases)
    self.seqfetcher = SeqFetcher()
    context_bases=self.context_bases)
  File "pipecycle/readclassifier.py", line 9, in __init__
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/seqfetcher.py", line 38, in __init__
  File "pipecycle/readclassifier.py", line 9, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
[E::fai_load3_core] Traceback (most recent call last):
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
  File "pipecycle/cohort.py", line 116, in count_reads_bam_file
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
    mon_cohort.count_reads_bam_file(bam_fofn_row, alteration, is_control, count, total_count, mon_output)
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
  File "pipecycle/shortvariant.py", line 29, in __init__
  File "pipecycle/cohort.py", line 62, in count_reads_bam_file
    context_bases=self.context_bases)
    self.variant_p = assembly_mapper.c_to_p(self.variant_c)
    context_bases=self.context_bases)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/assemblymapper.py", line 117, in c_to_p
  File "pipecycle/readclassifier.py", line 9, in __init__
  File "pipecycle/readclassifier.py", line 9, in __init__
    sr = SeqRepo(seqrepo_dir)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqrepo.py", line 58, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
  File "pipecycle/shortvariant.py", line 15, in __init__
    hdp = hgvs.dataproviders.uta.connect()
    self.aliases = SeqAliasDB(self._db_path, writeable=self._writeable)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 107, in connect
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqaliasdb/seqaliasdb.py", line 33, in __init__
    conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name, mode=mode, cache=cache)
OperationalError: unable to open database file
Failed to open FASTA index /usr/local/share/seqrepo/2018-08-21/sequences/2016/0824/100847/1472033327.587501.fa.bgz.gzi: Too many open files
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 477, in __init__
    super(UTA_postgresql, self).__init__(url, mode, cache)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 196, in __init__
    self.seqfetcher = SeqFetcher()
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/seqfetcher.py", line 38, in __init__
    sr = SeqRepo(seqrepo_dir)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqrepo.py", line 58, in __init__
    self.aliases = SeqAliasDB(self._db_path, writeable=self._writeable)
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/biocommons/seqrepo/seqaliasdb/seqaliasdb.py", line 33, in __init__
    super(ReadClassifier, self).__init__(gene, ref_seq_transcript, fmi_cds_effect, context_bases, is_print_alignment)
  File "pipecycle/shortvariant.py", line 15, in __init__
  File "pipecycle/shortvariant.py", line 15, in __init__
    hdp = hgvs.dataproviders.uta.connect()
  File "/Users/jfreidin/.pyenv/versions/pipecycle/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 107, in connect
```

**Comment by reece** [comment]
Have you tried running your code without closing connections?

The intended use is to open a connection at the start of processing and let
Python clean up the connections automatically when the entire process
terminates. By closing and reopening manually, you're actually doing a lot
of work that was never intended. A side effect of this might be that there
are orphaned connections to seqrepo. Since there is an upper limit on open
files, it could be that you're hitting that limit.

Please try running without explicitly closing the connections and report
back.

**Comment by jfreidin** [comment]
@reece, hdp.close() appears to release the postgreSQL connection, but may be leaving SeqRepo files open.

To your point I've modified my code to avoid creating/closing hdp connections on an object basis. I create a single hdp pooled connection per process, and that solved both the problem of running out of postgreSQL connections and open files.

**Comment by reece** [comment]
Your diagnosis is certainly correct about leaving seqrepo files open. I should probably just deprecate and (later) remove the `hdp.close()` method.

I'm glad that you're up and running smoothly. Thanks for confirming.
