### ISSUE TITLE
rsync: change_dir "/2018-11-26" (in seqrepo) failed: Permission denied (13)

### ISSUE THREAD

**Issue by davmlaw** [biocommons/hgvs#535]
```
$seqrepo -r /data/sacgf/reference/seqrepo pull

receiving incremental file list
rsync: change_dir "/2018-11-26" (in seqrepo) failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
Traceback (most recent call last):
  File "/usr/local/bin/seqrepo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/biocommons/seqrepo/cli.py", line 535, in main
    opts.func(opts)
  File "/usr/local/lib/python3.6/dist-packages/biocommons/seqrepo/cli.py", line 396, in pull
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/rsync', '-aHP', '--no-motd', 'dl.biocommons.org::seqrepo/2018-11-26/', '/data/sacgf/reference/seqrepo/2018-11-26.r0c3les2']' returned non-zero exit status 23.

```

**Comment by reece** [comment]
Sorry @davmlaw. I'm still working out kinks in the automation and missed a final chmod. Please try now. I'll close now, but please reopen if you're still having problems.
