### ISSUE TITLE
UTA connect Postgres url examples should contain schema 

### ISSUE THREAD

**Issue by davmlaw** [biocommons/hgvs#536]
uta.connect() Postgres urls require a schema, however the docstring and example documentation doesn't contain a schema.

https://hgvs.readthedocs.io/en/stable/modules/dataproviders.html#hgvs.dataproviders.uta.connect

> A local postgresql database:
>     postgresql://localhost/uta

Docstring on uta.connect says:

> A local postgresql database:
>     postgresql://localhost/uta

However, if you copy/paste these and try to use them you get:

```
In [23]: hdp = uta.connect(db_url="postgresql://@localhost/uta")
Exception: No schema name provided in postgresql://localhost/uta
```

Examples should be:

```
postgresql://localhost/uta/uta_20180821
```

**Comment by davmlaw** [comment]
Also, if you do this, then you get random errors printed to the screen (and when you exit ipython):

```
Exception ignored in: <bound method UTA_postgresql.__del__ of <hgvs.dataproviders.uta.UTA_postgresql object at 0x7f8a6491d0b8>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/hgvs/dataproviders/uta.py", line 480, in __del__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/hgvs/dataproviders/uta.py", line 483, in close
    if self.pooling:
AttributeError: 'UTA_postgresql' object has no attribute 'pooling'
```
