### ISSUE TITLE
Local UTA w/Postgres url throws exception: Generator didn't stop after throw

### ISSUE THREAD

**Issue by davmlaw** [biocommons/hgvs#537]
After following the local UTA and quick start:

https://hgvs.readthedocs.io/en/stable/quick_start.html

```
from hgvs.assemblymapper import AssemblyMapper
from hgvs.dataproviders import uta
import hgvs.parser

hgvsparser = hgvs.parser.Parser()
var_c1 = hgvsparser.parse_hgvs_variant('NM_001197320.1:c.281C>T')
hdp = uta.connect(db_url="postgresql://uta_admin:uta_admin@localhost/uta/uta_20180821")
variantmapper = AssemblyMapper(hdp, assembly_name="GRCh37")
var_g = variantmapper.c_to_g(var_c1)
```

This throws an exception:

```
/usr/local/lib/python3.6/dist-packages/hgvs/dataproviders/uta.py in get_tx_identity_info(self, tx_ac)
    351 
    352         """
--> 353         rows = self._fetchall(self._queries['tx_identity_info'], [tx_ac])
    354         if len(rows) == 0:
    355             raise HGVSDataNotAvailableError("No transcript definition for (tx_ac={tx_ac})".format(tx_ac=tx_ac))

/usr/local/lib/python3.6/dist-packages/hgvs/dataproviders/uta.py in _fetchall(self, sql, *args)
    216         with self._get_cursor() as cur:
    217             cur.execute(sql, *args)
--> 218             return cur.fetchall()
    219 
    220     ############################################################################

/usr/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
    124                     return False
    125                 raise
--> 126             raise RuntimeError("generator didn't stop after throw()")
    127 
    128 

RuntimeError: generator didn't stop after throw()
```

**Comment by davmlaw** [comment]
The Python spec for contextmanger says:

https://docs.python.org/2/library/contextlib.html

> The function being decorated must return a generator-iterator when called. This iterator must yield exactly one value

So you're not allowed to have a loop in there like you do for uta.UTA_postgresql._get_cursor

As a workaround I patched the HGVS code with:

```
        with self._get_cursor(n_retries=0) as cur:
```

Now I get a different error which I'll look into...

**Comment by davmlaw** [comment]
>> Please try exactly as below (i.e., removing the UTA connect string)

The issue only occurs with a local UTA w/Postgres url. It works fine for me when I don't provide an url can access the external UTA. 

The issue is in uta.UTA_postgresql._get_cursor - you need to trigger some kind of error, so that the looping occurs (it's the looping that violates the Python spec for contextmanager)

I'll run it through a debugger this morning and try and work out what my problem is, but whatever the error is, contextmanager shouldn't loop like that according to the Python specs.

**Comment by reece** [comment]
Simpler reproduction:

```
>>> from hgvs.dataproviders import uta
>>> hdp0 = uta.connect()
>>> hdp0.get_tx_identity_info("NM_000551.3")
['NM_000551.3', 'NM_000551.3', 'transcript', 213, 855, [553, 123, 3884], 'VHL']
>>> hdp1 = uta.connect("postgresql://uta.biocommons.org/uta_dev/uta_20180821")
>>> hdp1.get_tx_identity_info("NM_000551.3")
Traceback (most recent call last):
  File "<ipython-input-12-6f1de9d50b1e>", line 1, in <module>
    hdp1.get_tx_identity_info("NM_000551.3")
  File "/home/reece/projects/biocommons/hgvs/hgvs/decorators/lru_cache.py", line 186, in wrapper
    result = user_function(*args, **kwds)
  File "/home/reece/projects/biocommons/hgvs/hgvs/dataproviders/uta.py", line 350, in get_tx_identity_info
    rows = self._fetchall(self._queries['tx_identity_info'], [tx_ac])
  File "/home/reece/projects/biocommons/hgvs/hgvs/dataproviders/uta.py", line 215, in _fetchall
    return cur.fetchall()
  File "/usr/lib/python3.6/contextlib.py", line 126, in __exit__
    raise RuntimeError("generator didn't stop after throw()")
RuntimeError: generator didn't stop after throw()
```

I agree with your root cause analysis. However, I don't understand why these behave differently or why this issue hasn't caught more people. I'll continue to investigate.

**Comment by yangmqglobe** [comment]
I got this issue, too. It is related to the database, you should track back to the origin exception, which is
```
---------------------------------------------------------------------------
OperationalError                          Traceback (most recent call last)
/home/*user*/.software/miniconda3/envs/hgvs/lib/python3.7/site-packages/hgvs/dataproviders/uta.py in _get_cursor(self, n_retries)
    554 
--> 555                 yield cur
    556 

/home/*user*/.software/miniconda3/envs/hgvs/lib/python3.7/site-packages/hgvs/dataproviders/uta.py in _fetchall(self, sql, *args)
    216         with self._get_cursor() as cur:
--> 217             cur.execute(sql, *args)
    218             return cur.fetchall()

/home/*user*/.software/miniconda3/envs/hgvs/lib/python3.7/site-packages/psycopg2/extras.py in execute(self, query, vars)
    140         self._query_executed = 1
--> 141         return super(DictCursor, self).execute(query, vars)
    142 

OperationalError: materialized view "tx_def_summary_mv" has not been populated
HINT:  Use the REFRESH MATERIALIZED VIEW command.
```
I don't know why, but this is a database exception and I'm a freshman of Postgresql.
This occur when I load the 20180821 uta dump, but won't occur when I load 20161216 uta dump.

**Comment by andreas-invitae** [comment]
I had to patch the alignment of one transcript and prob should have updated the views afterwards. I'll try to re-run the export of the database.

**Comment by drifty914** [comment]
I'm getting the same error running locally as those above with uta_20180821 dated 2018-Dec-27 on the dl.biocommons.org site.

**Comment by davmlaw** [comment]
Same issue as [#218 which is now fixed](https://github.com/biocommons/uta/issues/218) which is now fixeed
